### ISSUE TITLE
Idea : Crowd solving regex

### ISSUE THREAD

**Issue by azman0101** [phikal/ReGeX#18]
Hi, I've just discovered this app. It's awsome...
What do you think about creating a database of solutions submitted by the users ?

After a while, a website with a search engine could make available the best result for the public...

The public could also submit problems which can be dispatched in the game for the best players.

What do you think ?

Bye

**Comment by phikal** [comment]
Thanks, it's always great to hear that people like the game.

Currently the tasks are generated randomly, which means that it's easy and fast to play offline - but *I do like your idea*.

What about this: you can select game modes in the settings: random and collective (what you suggested). Ignoring the potential for cheating, it would also serve as an interesting database for regex solutions. If wisely programmed, it also shouldn't make the app too large.

I'm going to take a look at the code again (was to lazy to work on it for a while), and after some cleaning up, I could implement a client interface. The server would take a bit more time to create, but it would also be doable.

Would/Can you contribute in any way (web design, server design, etc.)?

**Comment by nico202** [comment]
if someone helps with the UI, I could help developing the website frontend (ie angularjs) and maybe the server backend (PHP? Python? RoR?)

**Comment by phikal** [comment]
@nico202 What the server is implemented in is irrelevent, as long as we are sure how the data is transferred. All I ever worked on was node.js, so I consequently believe that JSON would be a good medium. But I don't know too much about other web platforms, so whatever you would be willing to help in would work. Maybe something with good regex solving speed, so the server could confirm the submission.

All this regex database would have to contain would be (main) tables: problems and solutions with number of times it would have been applied. The question would now be how to rate better and worse solutions. I don't belive that ReGeX's score algorithm would be of much help here, so maybe some democratic voting system? But that would require accounts of some sort, etc. 

I'm going to think about the infrastructure, maybe I'm going to come up with something usable. Other than that, I could also help with web design, but warning: it probably won't be the best looking site at first. :wink:

**Comment by phikal** [comment]
Latest commit: 244079a6c78641b09b3780c9ee3045839113d645

This was more work that it should have been, but I finally implemented a working web interface for what I provisionally call REDB (Regex Database). When connected to a server, it will ask `/newtask?diff=[difficulty]` for a new round, it will respond in JSON, ReGeX will process it and display. This of course has to be treaded, so that's why it took me so long because it was a bit of a fuss. 

**Anyway, the only things left for the v1.2 release are:**
* Submitting results to REDB over `/submit` (post request, uploading json)
* A game mode selection interface
* The REDB server itself.

I am planning on picking up the [The Go Programming Language](http://www.gopl.io/) soon, so I though about writing the server in Go, and use Docker to run it either on [AWS Elastic Beanstalk ](https://aws.amazon.com/elasticbeanstalk/), [Google Cloud Platform](https://cloud.google.com/) or some other PaaS. If anyone has any experiences in that field, I'd love some advice.

@nico202, so do you have experience with frontend development?

**Comment by phikal** [comment]
With 4b795347faf2e3a04e2f6f018fa28c32dcf0375b more or less all should be set (and I thought 244079a6c78641b09b3780c9ee3045839113d645 was a lot of work). The [website](https://github.com/phikal/REDB) had been written, and I will deploy in any day now. The main problem now will be adding tasks, because you accentually have to think do to that... But as soon as there are enough tasks (100-200?), I'll publish v1.3 on F-Droid hoping to attract contributers to REDB.

Anything I forgot? I hope not~
