### ISSUE TITLE
Conditional Regel working?

### ISSUE THREAD

**Issue by joesse** [phikal/ReGeX#43]
When I enter 
(C)(?(1)Y).
in the entry box I would expect that it matches 
CY
But instead the number on remaining characters is displayed red, which I interprete as "Syntax error in their expression". What am I missing?

**Comment by joesse** [comment]
Screenshot: https://www.dropbox.com/s/r4iqxchfy0n4jjt/sketch-1500560682795.png?dl=0

**Comment by phikal** [comment]
It's a simple mistake, and as you rightly guessed, it's because of a syntax error. As explain in the [javadocs](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html) of the Pattern class, groups that start with `(?...)`, are "Special Constructs" and require and addition character after the question mark to designate it's function. For example, `(?:...)` is a non-capturing group and `(?!...)` is a zero-width negative lookahead. 

What this means for your problem, is that you would have to either add another character after the question mark, delete the question mark from the expression, or try something different altogether. Assuming I didn't misunderstand the question, I'll close the issue then.

(PS. in case it's easier for you, I can also try and help you in German.)

**Comment by joesse** [comment]
Thanks for the javadoc link. There it says 

Perl constructs not supported by this class

...
The conditional constructs (?(condition)X) and (?(condition)X|Y),
...

That was what I was trying to do.  I'll have to try something different...
